"""
Snakefile for data analysis pipeline.
"""


BHSA_BASE_DATA = "/Users/cody/github/etcbc/bhsa/tf/2021"


rule build_corpus:
    params:
        book_limit="2_Kings"
    input:
        bhsa_data_path=BHSA_BASE_DATA,
        function_edits='data/bhsa_edits/function_edits.csv',
        object_edits='data/bhsa_edits/object_edits.json',
    output:
        "../data/data/corpus/{feature}.tf"
    script:
        "scripts/build_corpus.py"

