"""
Snakefile for source_data analysis pipeline.
"""

from pathlib import Path

HOME = Path.home()
BHSA_REPO = HOME / "github/etcbc/bhsa"
BHSA_BASE_DATA = BHSA_REPO / "tf/2021"
BHSA_GENRE_DATA = HOME / "github/etcbc/genre_synvar/tf/2021"


def globfiles(path, pattern):
    return Path(path).glob(pattern)


rule all:
    input:
        "../data/test.txt"


rule build_corpus:
    params:
        bhsa_repo=BHSA_REPO,
        bhsa_data_path=directory(BHSA_BASE_DATA),
        bhsa_genre_path=directory(BHSA_GENRE_DATA),
    input:
        "scripts/corpus_building/config.py",
        globfiles(BHSA_BASE_DATA, '*.tf'),
        globfiles(BHSA_GENRE_DATA, '*.tf'),
    output:
        directory("../data/corpus/")
    script:
        "scripts/build_corpus.py"


rule label_dataset:
    params:
        annotation_outdir="../data/annotations/blank",
        annotation_indir="../data/annotations/complete",
    input:
        corpus=rules.build_corpus.output,
        params="scripts/labeling/projects.py",
        sheet_params="scripts/labeling/annotation_sheets.py",
        completed_sheets=globfiles("../data/annotations/complete", "*.docx"),
    output:
        "../data/annotations/blank/test_1.0.docx",
    script:
        "scripts/label_dataset.py"
