"""
Snakefile for source_data analysis pipeline.
"""

import logging
from pathlib import Path

import snakemake

HOME = Path.home()
BHSA_REPO = HOME / "github/etcbc/bhsa"
BHSA_BASE_DATA = BHSA_REPO / "tf/2021"
BHSA_GENRE_DATA = HOME / "github/etcbc/genre_synvar/tf/2021"


def globfiles(path, pattern):
    return Path(path).glob(pattern)


rule build_corpus:
    params:
        bhsa_repo=BHSA_REPO,
        bhsa_data_path=directory(BHSA_BASE_DATA),
        bhsa_genre_path=directory(BHSA_GENRE_DATA),
    input:
        "scripts/corpus_building/config.py",
        "scripts/corpus_building/corpus_builder.py",
        "scripts/build_corpus.py",
        globfiles(BHSA_BASE_DATA, '.tf'),
        globfiles(BHSA_GENRE_DATA, '.tf'),
    output:
        directory("../data/corpus/")
    script:
        "scripts/build_corpus.py"
