\@LN{0}{10}
\@LN{0}{10}
\@LN{10}{10}
\@LN{1}{10}
\@LN{1}{10}
\@LN{2}{10}
\@LN{2}{10}
\@LN{3}{10}
\@LN{3}{10}
\@LN{4}{10}
\@LN{4}{10}
\@LN{5}{10}
\@LN{5}{12}
\@LN{6}{10}
\@LN{7}{10}
\@LN{8}{10}
\@LN{9}{10}
\@setckpt{Abstract/abstract}{
\@setckpt{Acknowledgement/acknowledgement}{
\@setckpt{Chapter1/chapter1}{
\@setckpt{Chapter3/chapter3}{
\@setckpt{Declaration/declaration}{
\@setckpt{Dedication/dedication}{
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lof}{\select@language {english}}
\@writefile{lot}{\addvspace {10\p@ }}
\@writefile{lot}{\addvspace {10\p@ }}
\@writefile{lot}{\select@language {english}}
\@writefile{toc}{\contentsline {chapter}{Bibliography}{3}{chapter*.1}\protected@file@percent }
\@writefile{toc}{\contentsline {chapter}{\numberline {1}Introduction}{1}{chapter.1}\protected@file@percent }
\@writefile{toc}{\contentsline {chapter}{\numberline {1}What are adverbs?}{1}{chapter.1}\protected@file@percent }
\@writefile{toc}{\contentsline {section}{\numberline {1.1}Parts of speech from a statistical perspective}{1}{section.1.1}\protected@file@percent }
\@writefile{toc}{\contentsline {section}{\numberline {1.1}The Connectionist Revolution}{1}{section.1.1}\protected@file@percent }
\@writefile{toc}{\select@language {english}}
\@writefile{toc}{\thispagestyle {empty}}
\AtEndDocument{\ifx\hyper@anchor\@undefined
\HyPL@Entry{0<</S/r>>}
\HyPL@Entry{1<</S/r /St 10>>}
\HyPL@Entry{2<</S/D>>}
\HyperFirstAtBeginDocument{\ifx\hyper@anchor\@undefined
\bibdata{References/references}
\bibstyle{apalike}
\fi}
\fi}
\gdef\HyperFirstAtBeginDocument#1{#1}
\gdef\contentsline#1#2#3#4{\oldcontentsline{#1}{#2}{#3}}
\gdef\newlabel#1#2{\newlabelxx{#1}#2}
\gdef\newlabelxx#1#2#3#4#5#6{\oldnewlabel{#1}{{#2}{#3}}}
\global\let\hyper@last\relax 
\global\let\oldcontentsline\contentsline
\global\let\oldnewlabel\newlabel
\let\contentsline\oldcontentsline
\let\newlabel\oldnewlabel
\providecommand \oddpage@label [2]{}
\providecommand*\HyPL@Entry[1]{}
\providecommand\HyperFirstAtBeginDocument{\AtBeginDocument}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\zref@newlabel[2]{}
\providecommand\zref@newlabel[2]{}
\providecommand\zref@newlabel[2]{}
\providecommand\zref@newlabel[2]{}
\providecommand\zref@newlabel[2]{}
\providecommand\zref@newlabel[2]{}
\providecommand\zref@newlabel[2]{}
\select@language {english}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@pps}{0}
\setcounter{@pps}{0}
\setcounter{@pps}{0}
\setcounter{@pps}{0}
\setcounter{@pps}{0}
\setcounter{@pps}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{1}
\setcounter{Hy@AnnotLevel}{0}
\setcounter{Hy@AnnotLevel}{0}
\setcounter{Hy@AnnotLevel}{0}
\setcounter{Hy@AnnotLevel}{0}
\setcounter{Hy@AnnotLevel}{0}
\setcounter{Hy@AnnotLevel}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{LN@truepage}{11}
\setcounter{LN@truepage}{11}
\setcounter{LN@truepage}{3}
\setcounter{LN@truepage}{5}
\setcounter{LN@truepage}{7}
\setcounter{LN@truepage}{9}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{bookmark@seq@number}{0}
\setcounter{bookmark@seq@number}{0}
\setcounter{bookmark@seq@number}{0}
\setcounter{bookmark@seq@number}{0}
\setcounter{bookmark@seq@number}{2}
\setcounter{bookmark@seq@number}{2}
\setcounter{caption@flags}{0}
\setcounter{caption@flags}{0}
\setcounter{caption@flags}{0}
\setcounter{caption@flags}{0}
\setcounter{caption@flags}{0}
\setcounter{caption@flags}{0}
\setcounter{chapter}{0}
\setcounter{chapter}{0}
\setcounter{chapter}{0}
\setcounter{chapter}{0}
\setcounter{chapter}{1}
\setcounter{chapter}{1}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{footdir@label}{0}
\setcounter{footdir@label}{0}
\setcounter{footdir@label}{0}
\setcounter{footdir@label}{0}
\setcounter{footdir@label}{0}
\setcounter{footdir@label}{2}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{1}
\setcounter{linenumber}{0}
\setcounter{linenumber}{0}
\setcounter{linenumber}{0}
\setcounter{linenumber}{0}
\setcounter{linenumber}{11}
\setcounter{linenumber}{5}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{page}{10}
\setcounter{page}{2}
\setcounter{page}{2}
\setcounter{page}{4}
\setcounter{page}{6}
\setcounter{page}{8}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{section@level}{0}
\setcounter{section@level}{0}
\setcounter{section@level}{0}
\setcounter{section@level}{0}
\setcounter{section@level}{1}
\setcounter{section@level}{1}
\setcounter{section}{0}
\setcounter{section}{0}
\setcounter{section}{0}
\setcounter{section}{0}
\setcounter{section}{1}
\setcounter{section}{1}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{tmpA}{0}
\setcounter{tmpA}{0}
\setcounter{tmpA}{0}
\setcounter{tmpA}{0}
\setcounter{tmpA}{0}
\setcounter{tmpA}{0}
\setcounter{tmpB}{0}
\setcounter{tmpB}{0}
\setcounter{tmpB}{0}
\setcounter{tmpB}{0}
\setcounter{tmpB}{0}
\setcounter{tmpB}{0}
\setcounter{tmpC}{0}
\setcounter{tmpC}{0}
\setcounter{tmpC}{0}
\setcounter{tmpC}{0}
\setcounter{tmpC}{0}
\setcounter{tmpC}{0}
\setcounter{tmpD}{0}
\setcounter{tmpD}{0}
\setcounter{tmpD}{0}
\setcounter{tmpD}{0}
\setcounter{tmpD}{0}
\setcounter{tmpD}{0}
\setcounter{tmpE}{0}
\setcounter{tmpE}{0}
\setcounter{tmpE}{0}
\setcounter{tmpE}{0}
\setcounter{tmpE}{0}
\setcounter{tmpE}{0}
\setcounter{tmpF}{0}
\setcounter{tmpF}{0}
\setcounter{tmpF}{0}
\setcounter{tmpF}{0}
\setcounter{tmpF}{0}
\setcounter{tmpF}{0}
\zref@newlabel{footdir@1}{\abspage{3}}
\zref@newlabel{footdir@2}{\abspage{3}}
}
}
}
}
}
}
